services:
  - type: web
    name: PARTEDISTRITOCUATRO
    runtime: docker
    plan: free
    autoDeploy: true
    healthCheckPath: /up
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: partedistritocuatro-db
          property: connectionString
      - key: DATA_DIR
        value: /var/data

databases:
  - name: partedistritocuatro-db
    databaseName: partedistritocuatro
    user: partedistrito
    plan: free
